upstream backend_upstream {

    # stable deployment
    server backend-blue:6000;

    # newer deployment
    server backend-green:6000;
}

server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    # API requests distributed across both backends
    location /api {
        proxy_pass http://backend_upstream;
    }

    # health requests also distributed
    location /health {
        proxy_pass http://backend_upstream/health;
    }
}