services:
  nginx:
    image: nginx
    ports:
      - "8000:80"
    volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always   

  app:
    image: python:3.11-alpine
    command: python -m http.server 3000 --bind 0.0.0.0
    ports:
      - "3000:3000"
    restart: always